### ISSUE TITLE
Error with Python

### ISSUE THREAD

**Issue by rojosinalma** [spf13/spf13-vim#110]
I don't really know why splunk is being considered on the error, im on OSX.
Honestly i don't know enough Python to debug this, but it seems to me that the problem is pretty small.

This shows up every time i open up vim from the console (on any file):

Error detected while processing /Users/<myusername>/.spf13-vim-3/.vim/bundle/python-mode/plugin/pymode.vim:
line  119:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/<myusername>/.spf13-vim-3/.vim/bundle/python-mode/pylibs/pymode/lint.py", line 2, in <module>
    import locale
  File "/Applications/splunk/lib/python2.7/locale.py", line 18, in <module>
    import operator
ImportError: /Applications/splunk/lib/python2.7/lib-dynload/operator.so: no appropriate 64-bit architecture (see "man python" for running in 32-bit mode)
line  230:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/<myusername>/.spf13-vim-3/.vim/bundle/python-mode/pylibs/ropevim.py", line 3, in <module>
    import tempfile
  File "/Applications/splunk/lib/python2.7/tempfile.py", line 34, in <module>
    from random import Random as _Random
  File "/Applications/splunk/lib/python2.7/random.py", line 45, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: /Applications/splunk/lib/python2.7/lib-dynload/math.so: no appropriate 64-bit architecture (see "man python" for running in 32-bit mode)

**Comment by jalama** [comment]
I see something similar  I have python 2.7.3.

Here's the error I get:

Error detected while processing /Users//.spf13-vim-3/.vim/bundle/python-mode/plugin/pymode.vim:
line  119:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users//.spf13-vim-3/.vim/bundle/python-mode/pylibs/pymode/auto.py", line 2, in <module>
    from pylibs.autopep8 import fix_file, PEP8_PASSES_MAX
  File "/Users//.spf13-vim-3/.vim/bundle/python-mode/pylibs/autopep8.py", line 41, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 34, in <module>
    from random import Random as _Random
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 47, in <module>
    from os import urandom as _urandom
ImportError: cannot import name urandom
line  230:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users//.spf13-vim-3/.vim/bundle/python-mode/pylibs/ropevim.py", line 3, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 34, in <module>
    from random import Random as _Random
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 47, in <module>
    from os import urandom as _urandom
ImportError: cannot import name urandom
Press ENTER or type command to continue

**Comment by yossiovadia** [comment]
Same here. waiting for a smart fella to give a solution

**Comment by scourgen** [comment]
Same here. need help.

**Comment by dnmiller** [comment]
At least some of this is due to homebrew linking issues. See the pymode FAQ:

https://github.com/klen/python-mode#id25

**Comment by spf13** [comment]
I got this response via email..

I follow this link and everything works fine.
http://stackoverflow.com/questions/10366821/python-importerror-cannot-import-urandom-since-ubuntu-12-04-upgrade

which also may help people.

**Comment by spf13** [comment]
It's pretty clear this is a python environment issue, not a spf13-vim specific issue. I'm going to close this issue, but hope that the links here will help anyone having similar issues. If I'm misunderstanding the issue, please reopen it with more information as to why this only happens in spf13-vim.
