### ISSUE TITLE
Issue with install, something about pymode

### ISSUE THREAD

**Issue by dmjio** [spf13/spf13-vim#176]
Hi, I installed this vanilla and have received this everytime I load up vim.
Any idea what my problem might be?

Error detected while processing /Users/Dave/.spf13-vim-3/.vim/bundle/python-mode/plugin/pymode.vim:
line  119:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Dave/.spf13-vim-3/.vim/bundle/python-mode/pylibs/pymode/auto.py", line 2, in <module>
    from pylibs.autopep8 import fix_file, PEP8_PASSES_MAX
  File "/Users/Dave/.spf13-vim-3/.vim/bundle/python-mode/pylibs/autopep8.py", line 41, in <module>
    import tempfile
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 34, in <module>
    from random import Random as _Random
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 47, in <module>
    from os import urandom as _urandom
ImportError: cannot import name urandom
line  230:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Dave/.spf13-vim-3/.vim/bundle/python-mode/pylibs/ropevim.py", line 3, in <module>
    import tempfile
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 34, in <module>
    from random import Random as _Random
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 47, in <module>
    from os import urandom as _urandom
ImportError: cannot import name urandom
Press ENTER or type command to continue

**Comment by tabuchid** [comment]
I've got the same issue

**Comment by dmjio** [comment]
I think I got mine fixed. Doug, do you have virtualenv installed? If so, source the python instance you use the most and try it again.

**Comment by martinogden** [comment]
This seems to be caused by a conflict between default python in OS X (10.8.2) install and homebrew installed python. Therefore, the error can be resolved by instructing vim to use the default python install by adding the following line to the `~/.vimrc.local` file:

`let $PYTHONHOME='/System/Library/Frameworks/Python.framework/Versions/Current'`

(or wherever the default install lives on your system.)

**Comment by spf13** [comment]
Thanks Martin!

I think this will help a lot of users.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by dmjio** [comment]
Martin, thanks a ton. This fixed it for good.

**Comment by barraponto** [comment]
@martinogden did you try `brew link`?

**Comment by g3nu1n3** [comment]
let $PYTHONHOME='/System/Library/Frameworks/Python.framework/Versions/Current'

This absolutely worked for me! Thank you martinogden. I believed this to be the issue after unlinking python and noticed that the error went away. Another thread was discussing macvim being the possible issue but I doubted it but entertained it which lead to my assumption.

Additionally the thread I reviewed said that urandom, possible some other modules, were built differently starting with python 2.7.3. Would be great if we would get an update to spf13 or the affected plugins to resolve for us novices :)

**Comment by pilot** [comment]
confirm this works for me at latest Mac OS X

**Comment by ghost** [comment]
I'm not a mac user so i have no experience with this. Can someone answer some questions for me?

Is this an issue in the most recent version of spf13-vim and related plugins?

If yes
1. how would you suggest we resolve this issue in a way that works for all spf13-vim users?
2. should a fix be applied to py-mode directly instead?
3. which version of python is the system python?
4. which version of python is the homebrew version?
