### ISSUE TITLE
Fails with python 2.7.4?

### ISSUE THREAD

**Issue by h3adache** [spf13/spf13-vim#338]
After installing python 2.7.4 on osx I get the following when trying to edit any files using vi or vim
Doesn't fail with macvim

```
vim ~/.ssh/known_hosts
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 278, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 253, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 243, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 472, in get_config_var
    return get_config_vars().get(name)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 405, in get_config_vars
    import re
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 105, in <module>
    import sre_compile
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 14, in <module>
    import sre_parse
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py", line 17, in <module>
    from sre_constants import *
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_constants.py", line 18, in <module>
    from _sre import MAXREPEAT
ImportError: cannot import name MAXREPEAT
```

**Comment by dcousineau** [comment]
I'm going to bump this issue, I'm having it namely when I run a `git commit` without the `-m` flag (e.g. on a merge), it fails with the same error message.

**Comment by orip** [comment]
The system's vim will die on plugins using Python.
A workaround is to always use MacVim, e.g. in .bashrc or .zshenv

```
export EDITOR="mvim -v"
export VISUAL="mvim -v"
```

or, to only affect git, edit .gitconfig

```
[core]
  editor = "mvim -v"
```

**Comment by dcousineau** [comment]
I've been using vim installed through home brew, would that change anything?
—

**Comment by phocean** [comment]
I am having the same issue, after installing python from homebrew. Remove python and no more issue.
I don't really understand what it is going on, any clarification would be welcomed. Thanks.

**Comment by pfitz** [comment]
Same for me - after deinstalling the 2.7.4 homebrew python everything was working again.

**Comment by iaculch** [comment]
I am having this issue when opening any .py file. Tried upgrading from python 2.72 to 2.74.

**Comment by dvreed77** [comment]
I am also having this issue with the Anaconda version of Python
