### ISSUE TITLE
Error when opening any python file

### ISSUE THREAD

**Issue by iaculch** [spf13/spf13-vim#427]
<code>"one.py" [New File]Traceback (most recent call last):
                                                       File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 548, in <module>
                                                                                                                                                                main()
                                                                                                                                                                        File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 530, in main
                                                                            known_paths = addusersitepackages(known_paths)
                                                                                                                            File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 266, in addusersitepackages
                                               user_site = getusersitepackages()
                                                                                  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 241, in getusersitepackages
     user_base = getuserbase() # this will also set USER_BASE
                                                               File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 231, in getuserbase
                                                                                                                                                                           USER_BASE = get_config_var('userbase')
                  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 516, in get_config_var
                                                                                                                                      return get_config_vars().get(name)
                                                                                                                                                                          File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 449, in get_config_vars
                                                                                              import re
                                                                                                         File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 105, in <module>
               import sre_compile
                                   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 14, in <module>
                                                                                                                                                  import sre_parse
                                                                                                                                                                    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py", line 17, in <module>
                                                                                from sre_constants import *
                                                                                                             File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_constants.py", line 18, in <module>
                             from _sre import MAXREPEAT
                                                       ImportError: cannot import name MAXREPEAT</code>

I am getting the above error when opening any python file. I have tried upgrading from python 2.72 to to 2.74

**Comment by reem** [comment]
I have the same error with python 2.7.5.
