### ISSUE TITLE
Python-mode problem with opening python files 

### ISSUE THREAD

**Issue by chrismatta** [spf13/spf13-vim#566]
I'm not sure if this is related to the PYTHONPATH issues previously brought up but whenever I attempt to open a python file I get the following errrors:

```
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in ?
  File "/users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/pymode/__init__.py", line 12
    from .autopep8 import fix_file
         ^
SyntaxError: invalid syntax
Error detected while processing function pymode#virtualenv#init:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in ?
NameError: name 'enable_virtualenv' is not defined
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line   10:
Traceback (most recent call last):
  File "<string>", line 1, in ?
  File "/users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/pymode/utils.py", line 28
    yield
        ^
SyntaxError: invalid syntax
Press ENTER or type command to continue
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in ?
Press ENTER or type command to continue
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/pymode/lint.py", line 3
Press ENTER or type command to continue
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from .environment import env
Press ENTER or type command to continue
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
         ^
Press ENTER or type command to continue
Error detected while processing /users/apps/dsm/a150495/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
SyntaxError: invalid syntax
Press ENTER or type command to continue
```

I'm using virtualenv and have set the following in my ~/.vimrc.local:

```
let $PYTHONHOME='/users/apps/dsm/a150495/.virtualenvs/default'
```

but it hasn't seemed to help. Does anyone have any ideas?

**Comment by spf13** [comment]
try :PymodeTroubleshooting
