### ISSUE TITLE
Always get error while opening a .py file after reinstalled spf13

### ISSUE THREAD

**Issue by kxxoling** [spf13/spf13-vim#739]
The Python version on my OS X 10.10.2 is 2.7.9, and I try to import `__future__` in python repl env. it's nothing wrong with it. Anybody has an idea?

Full log is below:

```
"app.py" 179L, 5723C
Error detected while processing /Users/windrunner/.spf13-vim-3/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/windrunner/.spf13-vim-3/.vim/bundle/python-mode/pymode/__init__.py", line 3, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
Error detected while processing /Users/windrunner/.spf13-vim-3/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line   12:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/windrunner/.spf13-vim-3/.vim/bundle/python-mode/pymode/__init__.py", line 3, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__
```

**Comment by verbal** [comment]
I am seeing this as well.

**Comment by mgoffin** [comment]
Also starting to see this.

**Comment by labeneator** [comment]
You may have recently installed a new python. Adjust your PATH to refer to your older python first. In my case, brew installed a python that broke pymode. I just added /usr/bin/ before /usr/local/bin/

**Comment by sldobri** [comment]
I just added /usr/bin/ before /usr/local/bin/ in my path,
