### ISSUE TITLE
CSAprrox needs gui support -- not loading

### ISSUE THREAD

**Issue by moos3** [spf13/spf13-vim#81]
I get this with a fresh installation of 3.0

```
[rgenthner@aaron:~] vim .vimrc.local 
CSApprox needs gui support - not loading.
  See :help |csapprox-+gui| for possible workarounds.
Press ENTER or type command to continue
```

But when I first do the installation i get this until i disable the python modules

```
[rgenthner@aaron:~/spf13-vim] vim ~/.vimrc 
CSApprox needs gui support - not loading.
  See :help |csapprox-+gui| for possible workarounds.
Error detected while processing /gpfs/gpfs0/devshare/home/rgenthner/.spf13-vim-3/.vim/bundle/python-mode/plugin/pymode.vim:
line  220:
Traceback (most recent call last):
  File "<string>", line 1, in ?
  File "/gpfs/gpfs0/devshare/home/rgenthner/.spf13-vim-3/.vim/bundle/python-mode/pylibs/ropevim.py", line 296
    arg = 'None' if prefix else ''
                  ^
SyntaxError: invalid syntax
Press ENTER or type command to continue
```

Ideas on why I would be getting this after a fresh install ? Box is running Centos 5.6. VIM version 7.2.148

**Comment by lenciel** [comment]
Same problem here. Just install vim-gtk and everything works fine after that.

`sudo apt-get install vim-gtk`

Note: I'm using Ubuntu.

**Comment by spf13** [comment]
I believe this issue has been resolved. Please reopen with more information if it is still an issue.
