### ISSUE TITLE
Pylint error when using spf13 with vim compiled with lua

### ISSUE THREAD

**Issue by willgdjones** [spf13/spf13-vim#959]
On a Mac OSX I've installed vim with lua support for autocompletion.

`brew install vim --with-lua`

Then installed spf13-vim.

`curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh`

Getting an error when I open a python file:

`Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fonz/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Press ENTER or type command to continue
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fonz/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 30, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fonz/.vim/bundle/python-mode/pymode/libs/pkg_resources/**init**.py", line 21, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import io

Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/fonz/anaconda/envs/heterogeneous/lib/python2.7/io.py", line 51, in <module>

Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import _io

Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: dlopen(/Users/fonz/anaconda/envs/heterogeneous/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
line    1:
  Referenced from: /Users/fonz/anaconda/envs/heterogeneous/lib/python2.7/lib-dynload/_io.so
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  Expected in: flat namespace
Error detected while processing /Users/fonz/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
 in /Users/fonz/anaconda/envs/heterogeneous/lib/python2.7/lib-dynload/_io.so`

Any ideas what could be the cause?

**Comment by willgdjones** [comment]
No issue when I install vim without lua support i.e. just:

`brew install vim`

**Comment by tthayer** [comment]
vim gets compiled using your system python so there might be a conflict with your virtualenv. What does your $PATH look like before and after sourcing your virtualenv?
